spring:
  application:
    name: greeting-service
  profiles:
    active: 'dev'
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Hello"
  default-value: "World"